<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKnNlVQr\Tramity_Apps_Backend_BackendKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKnNlVQr/Tramity_Apps_Backend_BackendKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerKnNlVQr.legacy');

    return;
}

if (!\class_exists(Tramity_Apps_Backend_BackendKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerKnNlVQr\Tramity_Apps_Backend_BackendKernelTestDebugContainer::class, Tramity_Apps_Backend_BackendKernelTestDebugContainer::class, false);
}

return new \ContainerKnNlVQr\Tramity_Apps_Backend_BackendKernelTestDebugContainer([
    'container.build_hash' => 'KnNlVQr',
    'container.build_id' => '4a794d04',
    'container.build_time' => 1671894538,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKnNlVQr');
