<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFl6yQhH\Tramity_Apps_Backend_BackendKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFl6yQhH/Tramity_Apps_Backend_BackendKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFl6yQhH.legacy');

    return;
}

if (!\class_exists(Tramity_Apps_Backend_BackendKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFl6yQhH\Tramity_Apps_Backend_BackendKernelTestDebugContainer::class, Tramity_Apps_Backend_BackendKernelTestDebugContainer::class, false);
}

return new \ContainerFl6yQhH\Tramity_Apps_Backend_BackendKernelTestDebugContainer([
    'container.build_hash' => 'Fl6yQhH',
    'container.build_id' => 'b7662bf5',
    'container.build_time' => 1671621071,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFl6yQhH');
