<?php

namespace ContainerObQFv85;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBehat_Mink_DefaultSessionService extends Tramity_Apps_Backend_BackendKernelTestDebugContainer
{
    /**
     * Gets the public 'behat.mink.default_session' shared service.
     *
     * @return \Behat\Mink\Session
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['behat.mink.default_session'] = $container->createProxy('SessionProxy9b5c0b7', fn () => \SessionProxy9b5c0b7::createLazyProxy(fn () => self::do($container, false)));
        }

        include_once \dirname(__DIR__, 6).'/vendor/behat/mink/src/Session.php';

        return ($container->services['behat.mink'] ?? $container->load('getBehat_MinkService'))->getSession();
    }
}
