<?php

namespace ContainerKnNlVQr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiRequestContextService extends Tramity_Apps_Backend_BackendKernelTestDebugContainer
{
    /**
     * Gets the public 'Tramity\Tests\shared\infrastructure\Behat\ApiRequestContext' shared autowired service.
     *
     * @return \Tramity\Tests\shared\infrastructure\Behat\ApiRequestContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 6).'/vendor/friends-of-behat/mink-extension/src/Behat/MinkExtension/Context/MinkAwareContext.php';
        include_once \dirname(__DIR__, 6).'/vendor/friends-of-behat/mink-extension/src/Behat/MinkExtension/Context/RawMinkContext.php';
        include_once \dirname(__DIR__, 6).'/tests/src/shared/infrastructure/Behat/ApiRequestContext.php';

        return $container->services['Tramity\\Tests\\shared\\infrastructure\\Behat\\ApiRequestContext'] = new \Tramity\Tests\shared\infrastructure\Behat\ApiRequestContext(($container->services['behat.mink.default_session'] ?? $container->load('getBehat_Mink_DefaultSessionService')));
    }
}
